# This workflow will build a Java project with Maven

name: Meet The Family

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven 3
      uses: aahmed-se/setup-maven@v3
      with:
        maven-version: 3.6.1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
